### PR TITLE
Resource: update icons

### LINKED ISSUE #97: Update indicator icon
### What Happened?

image

### Steps to Reproduce

1. Snooze night light
2. Look at Wingpanel indicator

### Expected Behavior

New icon.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Log Output

_No response_

### Hardware Info

_No response_

### PR DESCRIPTION
**Pull request by danirabbit**
Fixes #97 

Depends on:
- [x] https://github.com/elementary/icons/pull/1203
- [x] https://github.com/elementary/icons/pull/1204

### CODE REVIEW

**Review by lenemter — CHANGES_REQUESTED** [review]
The animation uses new icons, but after it the icon is old :(

**Comment by danirabbit** [comment]
Should be fixed now!

**Comment by lenemter** [comment]
@danirabbit I made sure to update icons and reinstall the indicator completely, but unfortunately the icon hasn't changed

**Comment by danirabbit** [comment]
@lenemter ah okay I see it. It should actually really be fixed now haha. Sorry!! Thanks for being thorough

**Review by lenemter — CHANGES_REQUESTED** [review]
The icon has changed! But i noticed that icon inside the popover has changed too:

image

Seems like the issue is that 48/disabled.svg misses the colored slashie. Can you color it too please?

**Comment by danirabbit** [comment]
@lenemter woops! Sorry about that. Didn't realize that one was also old. Should be updated now

**Review by lenemter — APPROVED** [review]
Great job! So nice to see all indicators are consistent now :tada:

**Pull request merged**
