### PR TITLE
Add dark style toggle to indicator

### PR DESCRIPTION
**Pull request by meisenzahl**
Closes https://github.com/elementary/wingpanel-indicator-nightlight/issues/71

### CODE REVIEW

**Comment by meisenzahl** [comment]
wingpanel-indicator-nightlight-add-dark-style-toggle-00

@danrabbit What do you think of the layout?

**Comment by meisenzahl** [comment]
Related to https://github.com/elementary/settings-daemon/pull/15

**Comment by fabiozaramella** [comment]
In my opinion it looks a bit cramped but it's still better than a separate indicator, since dark mode goes "logically" better along with night light.

**Comment by danrabbit** [comment]
I think we should probably group the link items together at the bottom

Screenshot from 2020-10-06 14 03 10@2x

And maybe dropping the separator between the slider and the switch would make these feel more logically grouped

**Comment by fabiozaramella** [comment]
What if we just drop the separator but keep the links divided? Since it makes sense for those to be separated.

**Comment by meisenzahl** [comment]
wingpanel-indicator-nightlight-add-dark-style-toggle-01

Like this?

**Comment by martinstork** [comment]
Quick phone edit:
image

Same order as the first image but separated by nightlight and dark mode might be an option.

**Comment by fabiozaramella** [comment]
How will it look as in @martinstork picture but keeping the separator between toggle/slider and the link to settings?

**Comment by meisenzahl** [comment]
> How would it look as in @martinstork picture but keeping the separator between toggle/slider and the link to settings? Maybe it would looks better while still being relatively homogeneous to other indicators' style.

@fabiozaramella you mean like this?

wingpanel-indicator-nightlight-add-dark-style-toggle-02

**Comment by meisenzahl** [comment]
Here are 2 more layouts, though I am not satisfied with them myself

wingpanel-indicator-nightlight-add-dark-style-toggle-03

wingpanel-indicator-nightlight-add-dark-style-toggle-04

**Comment by fabiozaramella** [comment]
> > How would it look as in @martinstork picture but keeping the separator between toggle/slider and the link to settings? Maybe it would looks better while still being relatively homogeneous to other indicators' style.
> 
> @fabiozaramella you mean like this?
> 
> wingpanel-indicator-nightlight-add-dark-style-toggle-02

Exactly, I think it's a good compromise. 😅

**Comment by fabiozaramella** [comment]
@elementary/ux any opinion on this?

**Comment by cassidyjames** [comment]
I want to think about what we want to actually have in an indicator, and when; i.e. should it have a light/dark style selection, or just a snooze option when dark style is scheduled? It works a little differently than Night Light so I want to be sure we're doing what people would expect here.

**Comment by hanaral** [comment]
> I want to think about what we want to actually have in an indicator, and when; i.e. should it have a light/dark style selection, or just a snooze option when dark style is scheduled? It works a little differently than Night Light so I want to be sure we're doing what people would expect here.

Maybe it shouldn't have a snooze at all? Since the dark style is not just something you toggle on and off like you would with a colour shift (in the case of colour checking). I think that the dark mode should only be able to be changed from Settings > Appearance, and that the indicator only has an obvious 'Dark Style Settings...' button.

**Comment by cassidyjames** [comment]
@hanaral I disagree. I toggle dark style on/off frequently on my phone depending on the context; e.g. if I bring my device into a dark room or outside into a bright environment. Having a quick toggle here would still be useful.

I think for a first go, we just stick to an option for dark or light, and have it disable the schedule if toggled. Then we can follow it up with smarter "snoozing" logic. So, something like:

```
--------------^---------------
| Snooze Night Light   (o-)  |
|                            |
| ☀️ --------------o-------  |
|                            |
|----------------------------|
|                            |
|        ☀️        🌑️        |
|      Default    Dark       |
|                            |
|----------------------------|
| Night Light Settings…      |
| Appearance Settings…       |
|----------------------------|
```

@danrabbit you had mentioned providing icons or illustrations at a smaller size for this, I think?

**Comment by hanaral** [comment]
> @hanaral I disagree. I toggle dark style on/off frequently on my phone depending on the context; e.g. if I bring my device into a dark room or outside into a bright environment. Having a quick toggle here would still be useful.

Hmm, I see. My argument was based on the idea that the environment wouldn't change, but I can see that moving a device around would require it.

**Comment by ChildishGiant** [comment]
I just spent the whole day making my own indicator, without checking if someone has already done it :facepalm: 
https://github.com/ChildishGiant/wingpanel-indicator-dark-style

**Comment by danirabbit** [comment]
Sorry this got stuck in review hell. Closing because we added dark style toggle to Quick Settings

**Pull request closed without merging**
